[project]
name = "satelitetracker2-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "requests>=2.34.2",
    "sgp4>=2.25",
    "sqlalchemy>=2.0.50",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "pydantic>=2.10.0",
    "httpx>=0.27.0",
    "pydantic-settings>=2.0.0",
    "apscheduler>=3.10.0",
    "passlib[bcrypt]>=1.7.4",
]
