"""Initial migration

Revision ID: 0dd95d232ec8
Revises: 
Create Date: 2026-06-12 14:27:02.992451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd95d232ec8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observer_stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellites',
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('intl_designator', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('norad_id')
    )
    op.create_table('tle_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.DateTime(), nullable=False),
    sa.Column('bstar', sa.Float(), nullable=False),
    sa.Column('inclination', sa.Float(), nullable=False),
    sa.Column('raan', sa.Float(), nullable=False),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('arg_perigee', sa.Float(), nullable=False),
    sa.Column('mean_anomaly', sa.Float(), nullable=False),
    sa.Column('mean_motion', sa.Float(), nullable=False),
    sa.Column('rev_num_at_epoch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.norad_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tle_data')
    op.drop_table('satellites')
    op.drop_table('observer_stations')
    # ### end Alembic commands ###
